version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: theplugs-app
        container_name: theplugs-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - theplugs-network

    db:
        image: mysql:8.0
        container_name: theplugs-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-theplugs}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_USER: ${DB_USERNAME:-theplugs}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/var/lib/mysql
        networks:
            - theplugs-network

networks:
    theplugs-network:
        driver: bridge
